site_name: "Moody Diagram Java Documentation"
nav:
  - Home: index.md
  - Theory: theory.md
  - README: README_COPY.md    
  - Screenshots:
      - Screenshot: screenshots/moody-diagram.png
  - Examples: sample-inputs.txt
theme:
  name: mkdocs
